spring.application.name=Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/hng_db
spring.datasource.username=pape
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

