services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_USER: pape
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: hng_db
    ports:
      - "3306:3306"
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  server:
    build:
      context: .
    ports:
      - "8080:8080"


volumes:
  db_data:
